name: fraud_detection_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.7.0
  - scipy=1.12.0
  - scikit-learn=1.2.2
  - tqdm=4.65.0
  - einops=0.7.0
  - pytorch=2.2.2
  - torchvision=0.15.1
  - torchaudio=2.2.2
  # 根据你的 CUDA 版本选择合适的 DGL 版本
  # 假设使用 CUDA 11.7
  - dgl-cuda117=0.9.0
  - accelerate=0.28.0
  - peft=0.4.0
  - deepspeed=0.14.0
  - sentencepiece=0.2.0
  - transformers=4.31.0
  - pip:
    - torch==2.2.2
    - torchvision==0.15.1